export enum QueryNames {
  GetAlbums = "GetAlbums",
  GetAlbumsPaged = "GetAlbumsPaged",
  GetAlbumById = "GetAlbumById",
  GetAlbumImages = "GetAlbumImages",
  GetEvents = "GetEvents",
  GetStorageImages = "GetStorageImages",
  GetVerse = "GetVerse",
  GetUsers = "GetUsers",
  GetAuthUsers = "GetAuthUsers",
  GetUsersWithoutAuth = "GetUsersWithoutAuth",
  GetUserProfile = "GetUserProfile",
  GetAccessRequests = "GetAccessRequests",
  GetAuditLogs = "GetAuditLogs",
}
