export enum MembershipFields {
  Code = "code",
  Fullname = "fullname",
  Birthdate = "birthdate",
  Gender = "gender",
  MaritalStatus = "maritalStatus",
  Address = "address",
  State = "state",
  City = "city",
  Neighborhood = "neighborhood",
  PostalCode = "postalCode",
  NativeOf = "nativeOf",
  NIF = "nif",
  DocId = "docId",
  Nationality = "nationality",
  Phone = "phone",
  Work = "work",
  Email = "email",
  MembershipType = "membershipType",
  IsActive = "isActive",
  MotherName = "motherName",
  FeatherName = "fatherName",
  Spouse = "spouse",
  WeddingDate = "weddingDate",
  Children = "children",
  ChildName = "childName",
  BaptismChurch = "baptismChurch",
  BaptismDate = "baptismDate",
  AdmissionType = "admissionType",
  BaptizedPastor = "baptizedPastor",
  AdmissionDate = "admissionDate",
  Congregation = "congregation",
  ChurchRole = "churchRole",
  BelongsTo = "belongsTo",
  Photo = "photo",
}

export enum GenderEnum {
  Male = 1,
  Female,
}

export enum MaritalStatusEnum {
  Married,
  Single,
  Divorced,
  StableUnion,
}
