import {
  createAlbum,
  deleteAlbum,
  deleteImageFromAlbum,
  getAlbumById,
  getAlbums,
  updateAlbum,
  uploadImage,
} from "./controllers/albumController";
import {deleteUploadedImage} from "./controllers/commonController";
import {
  createEvents,
  deleteEvents,
  getEvents,
  uploadEvent,
} from "./controllers/eventController";
import { createAuditLog, getAuditLogs } from "./controllers/auditController";
import {
  createNewMember,
  createUser,
  getUserProfile,
  getUsers,
  getAccessRequests,
  requestAccess,
  syncUserClaims,
  setUserRole,
  setUserActive,
  updateUserProfile,
  updateAccessRequestStatus,
  deleteAccessRequest,
} from "./controllers/userController";

export {
  createAuditLog,
  getAuditLogs,
  createAlbum,
  createEvents,
  createNewMember,
  createUser,
  deleteAlbum,
  deleteEvents,
  deleteImageFromAlbum,
  deleteUploadedImage,
  getUserProfile,
  getUsers,
  getAccessRequests,
  getAlbumById,
  getAlbums,
  getEvents,
  requestAccess,
  syncUserClaims,
  setUserRole,
  setUserActive,
  updateAlbum,
  updateUserProfile,
  updateAccessRequestStatus,
  deleteAccessRequest,
  uploadEvent,
  uploadImage,
};
